---
driver:
  name: vagrant


driver_config:
  require_chef_omnibus: 13

provisioner:
  name: chef_zero
  cookbook_path: ["~/.berkshelf/cookbooks/","#{current_dir}/cookbooks"]
  client_rb:
    environment: elevator-dev-1604

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[elevator::transcode]
    data_bags_path: "../../data_bags/"
    environments_path: "../../environments/"
    encrypted_data_bag_secret_key_path: "/Users/colin/Dropbox/data_bags/chef_encryption_key"
    attributes:
